name: Test Upload Artifact with SHA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dummy file
        run: |
          mkdir dist
          echo "hello world" > dist/test.txt

      - name: Upload artifact
        uses: actions/upload-artifacte654d4c6e659b45783a725dc92f1bfb0baa6c2de64b34e814dc206ff4aaaf
        with:
          name: test-artifact
          path: dist/test.txt
