name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt5 matplotlib

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "mapping.json:." --hidden-import=matplotlib --hidden-import=matplotlib.backends.backend_agg math_editor.py

      - name: List contents of dist folder
        run: dir dist

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: math-editor-win
          path: dist